services:
  app:
    extends:
      file: docker-compose.yaml
      service: app
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - db-data:/data

volumes:
  db-data:
