services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=/app/data/sqlite.db
    volumes:
      - ./data:/app/data
    command: >
      sh -c "bun --bun run migrate"
