# fly.toml app configuration file generated for astro-custom-auth on 2024-09-03T13:51:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'astro-custom-auth'
primary_region = 'ams'

[build]

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
DATABASE_URL = "/app/data/sqlite.db"
PORT = "4321"
MIGRATE = "true"

[mounts]
source = "data_volume"
destination = "/app/data"
