app = 'astro-custom-auth'
primary_region = 'ams'

[build]

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
DATABASE_URL = "/data/sqlite.db"
PORT = "4321"
MIGRATE = "true"

[mounts]
source = "litefs"
destination = "/var/lib/litefs"
